### ISSUE TITLE
Configuration missing error

### ISSUE THREAD

**Issue by timscott** [reasoncorp/dossier#33]
I just upgraded Rails 4 (4.1.1), and now in production when I try to run a report I get this error:

`Dossier::ConfigurationMissingError (No such file or directory - /app/config/dossier.yml`

Why is it looking under the `app` folder?  I do not get an error in my development environment.

**Comment by pboling** [comment]
@adamhunter This is rebroken in dossier 2.12.2.

```
rake aborted!
No such file or directory @ rb_sysopen - /app/config/dossier.yml. /app/config/dossier.yml must exist for Dossier to connect to the database.
/app/vendor/bundle/ruby/2.1.0/gems/dossier-2.12.2/lib/dossier/configuration.rb:32:in `rescue in setup_client!'
```
